[[formatter]]
name = "goimports"
flake = "nixpkgs#gotools"
binary = "goimports"
args = ["-srcdir", "{file}"]
mode = "stdin"

[[formatter]]
name = "gofumpt"
flake = "nixpkgs#gofumpt"
mode = "stdin"

[[formatter]]
name = "shfmt"
flake = "nixpkgs#shfmt"
args = ["-s", "-i=2"]
mode = "stdin"

[[formatter]]
name = "prettier"
flake = "nixpkgs#prettier"
args = ["--stdin-filepath", "{file}"]
mode = "stdin"

[[formatter]]
name = "jq"
flake = "nixpkgs#jq"
args = ["."]
mode = "stdin"

[[formatter]]
name = "rustfmt"
flake = "nixpkgs#rustfmt"
mode = "stdin"

[[formatter]]
name = "tommy"
flake = "github:amarbel-llc/tommy"
args = ["fmt", "-"]
mode = "stdin"

[[formatter]]
name = "pandoc"
flake = "nixpkgs#pandoc"
args = ["--columns=80", "-f", "markdown", "-t", "markdown", "--standalone"]
mode = "stdin"
