#! /usr/bin/env -S bash -e

: "${XDG_STATE_HOME:=$HOME/.local/state}"

dir_log="$XDG_STATE_HOME/rcm"
mkdir -p "$dir_log"
log="$dir_log/log"

touch "$log"

while IFS= read -r output; do
  rm -f "$output"
done < <(sort -u <"$log")

rm "$log"

function format_with_vim() {
  true
  # vim \
  #   -e \
  #   -s \
  #   --clean \
  #   -c 'normal gg=G' \
  #   -c 'wq' \
  #   "$1" \
  #   </dev/null
}

# jinja
while IFS= read -r -d '' template; do
  output="${template%.j2}"
  # TODO change to `.j2-json` extension
  values_literal="$template.json"

  # TODO change to `.j2-script` extension
  values_script="$template.json-script"
  output_buffer="$(mktemp)"

  {
    echo "# AUTOGENERATED BY \`$(realpath "$0")\`"

    if [[ -f $values_script ]]; then
      chmod +x "$values_script"

      if ! "$values_script" | jinja2 "$template"; then
        echo "\`$values_script\` failed" >&2
        continue
      fi

      rm "$values_script"
    elif [[ -f $values_literal ]]; then
      if ! jinja2 "$template" "$values_literal" 2>/dev/null; then
        echo "failed to parse \`$values_literal\` failed" >&2
        continue
      fi

      rm "$values_literal"
    else
      echo "expected values file \`$values_literal\` or \`$values_script\` for \`$output\`" >&2
      continue
    fi
  } >"$output_buffer"

  format_with_vim "$output_buffer"
  mv "$output_buffer" "$output"
  rm "$template"

  echo "$output" >>"$log"

done < <(find "$HOME"/.* -name .Trash -prune -o -iname '*.j2' -a -print0 | sort -z)

# rcm-script
while IFS= read -r -d '' template; do
  output="${template%.rcm-script}"
  output_buffer="$(mktemp)"

  if [[ ! -x $template ]]; then
    echo "template file not executable: \`$template\`" >&2
    continue
  fi

  {
    echo "# AUTOGENERATED BY \`$(realpath "$0")\`"
    "$template"
  } >"$output_buffer"

  format_with_vim "$output_buffer"
  mv "$output_buffer" "$output"

  rm "$template"

  echo "$output" >>"$log"

done < <(find "$HOME"/.* -name .Trash -prune -o -iname '*.rcm-script' -a -print0 | sort -z)
