#! /usr/bin/env -S bash -e
# @brief generates config files from .j2, .json, .json-script, and .rcm-script

# TODO fix performance of this hook (lsrc seems to be very slow now because of
# extra dotfiles

: "${XDG_STATE_HOME:=$HOME/.local/state}"
export PATH="$HOME/eng/result/bin:$PATH"

dir_log="$XDG_STATE_HOME/rcm"
mkdir -p "$dir_log"
log="$dir_log/log"

touch "$log"

while IFS= read -r output; do
  rm -f "$output"
done < <(sort -u <"$log")

rm "$log"

gum log -l info "processing templates and logging to $log"

function format_with_vim() {
  true
  # vim \
  #   -e \
  #   -s \
  #   --clean \
  #   -c 'normal gg=G' \
  #   -c 'wq' \
  #   "$1" \
  #   </dev/null
}

# Find template destination paths by searching the source dotfiles directory
# and checking if rcup deployed the corresponding dotfile. This avoids calling
# lsrc which scans the entire home directory.
dotfiles_dir="$HOME/eng/rcm"

function dotfile_destination() {
  local src="$1"
  local rel="${src#"$dotfiles_dir"/}"

  # Strip tag-<tag>/ prefix if present
  if [[ $rel == tag-*/* ]]; then
    rel="${rel#tag-*/}"
  fi

  echo "$HOME/.$rel"
}

function find_templates() {
  local pattern="$1"

  while IFS= read -r src; do
    local dest
    dest="$(dotfile_destination "$src")"

    if [[ -f $dest ]]; then
      echo "$dest"
    fi
  done < <(find "$dotfiles_dir" -name "$pattern" -not -path '*/hooks/*' | sort)
}

EXT_J2="j2"
EXT_J2_JSON="json"          # TODO change to `.j2.json` extension
EXT_J2_SCRIPT="json-script" # TODO change to `.j2.script` extension

# j2
while IFS= read -r template; do
  gum log -l info "processing jinja template $template"

  output="${template%".$EXT_J2"}"
  values_literal="$template.$EXT_J2_JSON"
  values_script="$template.$EXT_J2_SCRIPT"
  output_buffer="$(mktemp)"

  gum log -l debug "template: $template"
  gum log -l debug "output: $output"
  gum log -l debug "values_literal: $values_literal"
  gum log -l debug "values_script: $values_script"

  {
    echo "# AUTOGENERATED BY \`$(realpath "$0")\`"
    echo "# USING \`$(realpath "$template")\`"

    if [[ -f $values_script ]]; then
      chmod +x "$values_script"

      if ! "$values_script" | jinja2 "$template"; then
        gum log -l warn "\`$values_script\` failed" >&2
        continue
      fi

      rm "$values_script"
    elif [[ -f $values_literal ]]; then
      if ! jinja2 "$template" "$values_literal" 2>/dev/null; then
        gum log -l warn "failed to parse \`$values_literal\` failed" >&2
        continue
      fi

      rm "$values_literal"
    else
      gum log -l warn "expected values file \`$values_literal\` or \`$values_script\` for \`$output\`" >&2
      continue
    fi
  } >"$output_buffer"

  format_with_vim "$output_buffer"
  mv "$output_buffer" "$output"
  rm "$template"

  echo "$output" >>"$log"

done < <(find_templates "*.$EXT_J2")

EXT_RCM_SCRIPT="rcm-script"

# rcm-script
while IFS= read -r template; do
  gum log -l info "processing script template $template"

  output="${template%".$EXT_RCM_SCRIPT"}"
  output_buffer="$(mktemp)"

  if [[ ! -x $template ]]; then
    gum log -l warn "template file not executable: \`$template\`" >&2
    continue
  fi

  {
    echo "# AUTOGENERATED BY \`$(realpath "$0")\`"
    echo "# USING \`$(realpath "$template")\`"
    "$template"
  } >"$output_buffer"

  format_with_vim "$output_buffer"
  mv "$output_buffer" "$output"

  rm "$template"

  echo "$output" >>"$log"

done < <(find_templates "*.$EXT_RCM_SCRIPT")
