#! /usr/bin/env -S bash -e

our_bash="$(readlink "$HOME/eng/result/bin/bash")"
mkdir -p ~/.config/direnv/
cat - > ~/.config/direnv/direnv.toml <<-EOM
# AUTOGENERATED BY \`$(realpath "$0")\`. DO NOT EDIT.

bash_path = "$our_bash"

[whitelist]
prefix = ["$HOME/eng"]
EOM
