#! /usr/bin/env -S bash -e

FILE_TPL="$HOME/.config/gnupg/scdaemon.conf.tpl"
FILE_CONFIG="$HOME/.config/gnupg/scdaemon.conf"

if [[ ! -f "$FILE_TPL" ]]; then
  return
fi

# use `/usr/sbin/ldconfig` to avoid nix
FILE_PCSC_DRIVER="$(/usr/sbin/ldconfig -p | grep libpcsclite | awk '{print $4}' | head -1)"

if [[ ! -f "$FILE_PCSC_DRIVER" ]]; then
  echo "System PCSC_DRIVER (\`$FILE_PCSC_DRIVER\`) not found." >&2
  exit 1
fi

echo "# AUTOGENERATED BY \`$(realpath "$0")\`" > "$FILE_CONFIG"
sed "s#PCSC_DRIVER#$FILE_PCSC_DRIVER#" "$FILE_TPL" >> "$FILE_CONFIG"

