#! /usr/bin/env -S bash -e

: "${XDG_STATE_HOME:=$HOME/.local/state}"

dir_log="$XDG_STATE_HOME/rcm_j2"
mkdir -p "$dir_log"
log="$dir_log/log"

touch "$log"

while IFS= read -r output; do
  rm -f "$output"
done < <(sort -u <"$log")

rm "$log"

while IFS= read -r -d '' template; do
  output="${template%.j2}"
  values="$template.json"

  {
    echo "# AUTOGENERATED BY \`$(realpath "$0")\`"

    if [[ -x $values ]]; then
      "$values" | jinja2 "$template" - 2>/dev/null
    elif [[ -f $values ]]; then
      jinja2 "$template" "$values" 2>/dev/null
    else
      jinja2 "$template" 2>/dev/null
    fi
  } >"$output"

  echo "$output" >>"$log"

done < <(find "$HOME"/.* -name .Trash -prune -o -iname '*.j2' -a -print0 | sort -z)
