#! /usr/bin/env -S bash -e

git_root="$(git rev-parse --show-toplevel)"

: "${XDG_STATE_HOME:=$HOME/.local/state}"

dir_log="$XDG_STATE_HOME/rcm_j2"
mkdir -p "$dir_log"
log="$dir_log/log"

while IFS= read -r -d '' template
do
  output="${template%.j2}"
  values="$template.json"

  if [[ -x "$values" ]]; then
    {
      echo "# AUTOGENERATED BY \`$(realpath "$0")\`"
      "$values" | j2 "$template" - 2>/dev/null
    } > "$output"
  elif [[ -f "$values" ]]; then
    {
      echo "# AUTOGENERATED BY \`$(realpath "$0")\`"
      j2 "$template" "$values" 2>/dev/null
    } > "$output"
  else
    {
      echo "# AUTOGENERATED BY \`$(realpath "$0")\`"
      j2 "$template" 2>/dev/null
    } > "$output"
  fi

  echo "$output" >> "$log"

done < <(find $HOME/.* -name .Trash -prune -o -iname '*.j2' -a -print0)
