
timg-preview:
  timg -pk -I -U --center --clear -W -

preview-zit-object-timg target format:
  #! /bin/bash -e
  pushd "{{invocation_directory()}}" >/dev/null 2>&1
  zit format-blob {{target}} {{format}} | timg -pk -I -U --center --clear -W -

preview-zit-object target format:
  #! /bin/bash -e
  pushd "{{invocation_directory()}}" >/dev/null 2>&1
  zit format-blob {{target}} {{format}}

mr-build-and-watch target script:
  #! /bin/bash -e
  pushd "{{invocation_directory()}}" >/dev/null 2>&1
  fswatch --event Updated -o {{target}} | xargs -I {} bash -c '{{script}}'
